/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'EchoWine' at '05/10/16 23.59' with Gradle 2.14.1
 *
 * @author EchoWine, @date 05/10/16 23.59
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
